# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AERONAUTICAL INFORMATION', 'Aeronautical Information'), ('METEOROLOGY', 'Meteorology'), ('ENVIRONMENT', 'Environment'), ('CAPACITY DEMAND AND FLOW', 'Capacity Demand and Flow'), ('SURVEILLANCE', 'Surveillance'), ('OTHER', 'Other')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'flight category',
                'verbose_name_plural': 'flight categories',
            },
        ),
        migrations.CreateModel(
            name='FlightPhaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AIRPORT RAMP', 'Airport (ramp)'), ('TAKE OFF', 'Take Off'), ('DEPARTURE', 'Departure'), ('EN-ROUTE', 'En-route'), ('OCEANIC', 'Oceanic'), ('ARRIVAL', 'Arrival')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'flight phase category',
                'verbose_name_plural': 'flight phases categories',
            },
        ),
        migrations.CreateModel(
            name='RegionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AFRICA', 'Africa'), ('ASIA', 'Asia'), ('EUROPE', 'Europe'), ('GLOBAL', 'Global'), ('NORTH AMERICA', 'North America'), ('OCEANIA', 'Oceania'), ('SOUTH AMERICA', 'South America')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'region category',
                'verbose_name_plural': 'region categories',
            },
        ),
        migrations.CreateModel(
            name='StakeholderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AIRPORT OPERATOR', 'Airport Operator'), ('AIRSPACE USER', 'Airspace User'), ('ANSP', 'ANSP'), ('NETWORK MANAGER', 'Network Manager')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'stakeholder category',
                'verbose_name_plural': 'stakeholder categories',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AIRM MODEL', 'AIRM Model'), ('COMPLIANCE REFERENCE DOCUMENT', 'Compliance Reference Document'), ('CONTACT POINT', 'Contact Point'), ('ORGANISATION DOCUMENT', 'Organisation Document'), ('GENERAL DOCUMENT', 'General Document'), ('INFORMATION REFERENCE DOCUMENT', 'Information Reference Document'), ('INFRASTRUCTURE PROFILE', 'Infrastructure Profile'), ('REFERENCE DOCUMENT', 'Reference Document'), ('INFRASTRUCTURE STANDARD', 'Infrastructure Standard'), ('INTERFACE', 'Interface'), ('ORGANISATION', 'Organisation'), ('PROPRIETARY DATA EXCHANGE FORMAT', 'Proprietary Data Exchange Format'), ('SERVICE IMPLEMENTATION', 'Service Implementation'), ('SERVICE COMPLIANCE CLAIM', 'Service Compliance Claim'), ('SERVICE DEFINITION', 'Service Definition'), ('SERVICE DEFINITION PROGRESS', 'Service Definition Progress'), ('SERVICE DOCUMENT', 'Service Document'), ('SERVICE END POINT', 'Service End Point'), ('SERVICE LOGICAL MODEL', 'Service Logical Model'), ('SERVICE REFERENCE DOCUMENT', 'Service Reference Document'), ('DATA STANDARD', 'Data Standard')], max_length=50, unique=True)),
            ],
        ),
    ]
