# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(default='services/images/contact_points/none/default.jpg', null=True, upload_to='services/images/contact_points/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureReferenceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='infrastructure/documents/')),
                ('image', models.ImageField(default='infrastructure/images/none/default.jpg', null=True, upload_to='infrastructure/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='participants/documents/')),
                ('image', models.ImageField(default='participants/images/documents/none/default.jpg', null=True, upload_to='participants/images/documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='swim/documents/')),
                ('image', models.ImageField(default='swim_registry/images/none/default.jpg', null=True, upload_to='swim/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('activity_categories', models.ManyToManyField(related_name='services', to='registry.ActivityCategory')),
                ('contact_points', models.ManyToManyField(related_name='services', to='registry.ContactPoint')),
                ('data_categories', models.ManyToManyField(related_name='services', to='registry.DataCategory')),
                ('flight_phases', models.ManyToManyField(related_name='services', to='registry.FlightPhaseCategory')),
                ('implementation_maturity', models.ManyToManyField(related_name='services', to='registry.ImplementationMaturityCategory')),
                ('implementation_status', models.ManyToManyField(related_name='services', to='registry.ImplementationStatusCategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='community.Participant')),
                ('regions', models.ManyToManyField(related_name='services', to='registry.RegionCategory')),
                ('registration_status', models.ManyToManyField(related_name='services', to='registry.RegistrationStatusCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='services/documents/')),
                ('image', models.ImageField(default='services/images/documents/none/default.jpg', null=True, upload_to='services/images/documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('infrastructure_reference_documents', models.ManyToManyField(related_name='technical_interfaces', to='registry.InfrastructureReferenceDocument')),
                ('service_documents', models.ManyToManyField(related_name='technical_interfaces', to='registry.ServiceDocument')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_documentation',
            field=models.ManyToManyField(related_name='services', to='registry.ServiceDocument'),
        ),
        migrations.AddField(
            model_name='service',
            name='stakeholders',
            field=models.ManyToManyField(related_name='services', to='registry.StakeholderCategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='technical_interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.TechnicalInterface'),
        ),
        migrations.AddField(
            model_name='service',
            name='version_category',
            field=models.ManyToManyField(related_name='services', to='registry.VersionCategory'),
        ),
    ]
