# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20170518_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExchangeFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='data/data_exchange_formats/images/none/default.jpg', upload_to='data/data_exchange_formats/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='data/data_standards/images/none/default.jpg', upload_to='data/data_standards/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='swim/documents/')),
                ('image', models.ImageField(default='swim/documents/images/none/default.jpg', null=True, upload_to='swim/documents/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='services/end_points/images/none/default.jpg', upload_to='services/end_points/images/')),
                ('address', models.URLField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='infrastructure/profiles/images/none/default.jpg', upload_to='infrastructure/profiles/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='infrastructure/documents/')),
                ('image', models.ImageField(default='infrastructure/documents/images/none/default.jpg', null=True, upload_to='infrastructure/documents/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='infrastructure/profiles/images/none/default.jpg', upload_to='infrastructure/profiles/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalInterfaceBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='infrastructure/technical_interface_bindings/images/none/default.jpg', upload_to='infrastructure/technical_interface_bindings/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='infrastructurereferencedocument',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participantdocument',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/images/profiles/none/default.jpg', upload_to='services/images/profiles/'),
        ),
        migrations.AddField(
            model_name='servicedocument',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='image',
            field=models.ImageField(default='services/technical_interfaces/images/none/default.jpg', upload_to='services/technical_interfaces/images/'),
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='image',
            field=models.ImageField(default='services/contact_points/images/none/default.jpg', null=True, upload_to='services/contact_points/images/'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='document',
            field=models.FileField(upload_to='infrastructure/reference_documents/'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='image',
            field=models.ImageField(default='infrastructure/reference_documents/images/none/default.jpg', null=True, upload_to='infrastructure/reference_documents/images/'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='image',
            field=models.ImageField(default='participants/documents/images/none/default.jpg', null=True, upload_to='participants/documents/images/'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='document',
            field=models.FileField(upload_to='swim/reference_documents/'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='image',
            field=models.ImageField(default='swim/reference_documents/images/none/default.jpg', null=True, upload_to='swim/reference_documents/images/'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='image',
            field=models.ImageField(default='services/documents/images/none/default.jpg', null=True, upload_to='services/documents/images/'),
        ),
        migrations.AddField(
            model_name='infrastructureprofile',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(related_name='infrastructure_profiles', to='registry.InfrastructureReferenceDocument'),
        ),
        migrations.AddField(
            model_name='infrastructureprofile',
            name='technical_interface_bindings',
            field=models.ManyToManyField(related_name='infrastructure_profiles', to='registry.TechnicalInterfaceBinding'),
        ),
        migrations.AddField(
            model_name='infrastructuredescription',
            name='infrastructure_documents',
            field=models.ManyToManyField(related_name='infrastructure_description', to='registry.InfrastructureDocument'),
        ),
        migrations.AddField(
            model_name='infrastructuredescription',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(related_name='infrastructure_description', to='registry.InfrastructureReferenceDocument'),
        ),
        migrations.AddField(
            model_name='infrastructuredescription',
            name='technical_interface_bindings',
            field=models.ManyToManyField(related_name='infrastructure_description', to='registry.TechnicalInterfaceBinding'),
        ),
        migrations.AddField(
            model_name='datastandard',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(related_name='data_standards', to='registry.InfrastructureReferenceDocument'),
        ),
        migrations.AddField(
            model_name='dataexchangeformat',
            name='infrastructure_documents',
            field=models.ManyToManyField(related_name='data_exchange_formats', to='registry.InfrastructureDocument'),
        ),
        migrations.AddField(
            model_name='dataexchangeformat',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(related_name='data_exchange_formats', to='registry.InfrastructureReferenceDocument'),
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='data_exchange_formats',
            field=models.ManyToManyField(related_name='technical_interfaces', to='registry.DataExchangeFormat'),
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='data_standards',
            field=models.ManyToManyField(related_name='technical_interfaces', to='registry.DataStandard'),
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='end_points',
            field=models.ManyToManyField(related_name='technical_interfaces', to='registry.EndPoint'),
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='infrastructure_description',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='technical_interfaces', to='registry.InfrastructureDescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='infrastructure_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='technical_interfaces', to='registry.InfrastructureProfile'),
            preserve_default=False,
        ),
    ]
