# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20170518_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='applications/documents/')),
                ('image', models.ImageField(default='applications/documents/images/none/default.jpg', null=True, upload_to='applications/documents/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_documentation',
            new_name='documents',
        ),
    ]
