# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20170518_2344'),
        ('registry', '0004_auto_20170519_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('image', models.ImageField(default='applications/images/profiles/none/default.jpg', upload_to='applications/images/profiles/')),
                ('opensource', models.BooleanField(default=False)),
                ('payable', models.BooleanField(default=False)),
                ('activity_categories', models.ManyToManyField(related_name='applications', to='registry.ActivityCategory')),
                ('consumed_services', models.ManyToManyField(related_name='applications', to='registry.Service')),
                ('contact_points', models.ManyToManyField(related_name='applications', to='registry.ContactPoint')),
                ('data_categories', models.ManyToManyField(related_name='applications', to='registry.DataCategory')),
                ('data_exchange_formats', models.ManyToManyField(related_name='applications', to='registry.DataExchangeFormat')),
                ('data_standards', models.ManyToManyField(related_name='applications', to='registry.DataStandard')),
                ('documents', models.ManyToManyField(related_name='applications', to='registry.ApplicationDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='applications/files/')),
                ('image', models.ImageField(default='applications/files/images/none/default.jpg', null=True, upload_to='applications/files/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='files',
            field=models.ManyToManyField(related_name='applications', to='registry.ApplicationFile'),
        ),
        migrations.AddField(
            model_name='application',
            name='flight_phases',
            field=models.ManyToManyField(related_name='applications', to='registry.FlightPhaseCategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_maturity',
            field=models.ManyToManyField(related_name='applications', to='registry.ImplementationMaturityCategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_status',
            field=models.ManyToManyField(related_name='applications', to='registry.ImplementationStatusCategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='community.Participant'),
        ),
        migrations.AddField(
            model_name='application',
            name='regions',
            field=models.ManyToManyField(related_name='applications', to='registry.RegionCategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='registration_status',
            field=models.ManyToManyField(related_name='applications', to='registry.RegistrationStatusCategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='stakeholders',
            field=models.ManyToManyField(related_name='applications', to='registry.StakeholderCategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='version_category',
            field=models.ManyToManyField(related_name='applications', to='registry.VersionCategory'),
        ),
    ]
