# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20170520_1849'),
        ('registry', '0005_auto_20170519_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='community.Profile')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows_from', to='registry.RegistrationStatusCategory')),
                ('next_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows_to', to='registry.RegistrationStatusCategory')),
                ('previous_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='application',
            name='implementation_maturity',
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_maturity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.ImplementationMaturityCategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='application',
            name='implementation_status',
        ),
        migrations.AddField(
            model_name='application',
            name='implementation_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.ImplementationStatusCategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='application',
            name='registration_status',
        ),
        migrations.AddField(
            model_name='application',
            name='registration_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.RegistrationStatusCategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='application',
            name='version_category',
        ),
        migrations.AddField(
            model_name='application',
            name='version_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.VersionCategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='service',
            name='implementation_maturity',
        ),
        migrations.AddField(
            model_name='service',
            name='implementation_maturity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.ImplementationMaturityCategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='service',
            name='implementation_status',
        ),
        migrations.AddField(
            model_name='service',
            name='implementation_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.ImplementationStatusCategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='service',
            name='registration_status',
        ),
        migrations.AddField(
            model_name='service',
            name='registration_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.RegistrationStatusCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='technical_interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='registry.TechnicalInterface'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='version_category',
        ),
        migrations.AddField(
            model_name='service',
            name='version_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.VersionCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='workflow',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='registry.Workflow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='workflow',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='registry.Workflow'),
            preserve_default=False,
        ),
    ]
