# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20170521_1401'),
        ('registry', '0006_auto_20170520_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExchangeFormatApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='data/data_exchange_formats/images/none/default.jpg', upload_to='data/data_exchange_formats/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataExchangeFormatApplicationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='infrastructure/documents/data_exchange_formats/')),
                ('image', models.ImageField(default='infrastructure/documents/data_exchange_formats/images/none/default.jpg', null=True, upload_to='infrastructure/documents/data_exchange_formats/images/')),
                ('data_exchange_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.DataExchangeFormatApplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataExchangeFormatService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='data/data_exchange_formats/images/none/default.jpg', upload_to='data/data_exchange_formats/images/')),
                ('infrastructure_reference_documents', models.ManyToManyField(to='registry.InfrastructureReferenceDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataExchangeFormatServiceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='infrastructure/documents/data_exchange_formats/')),
                ('image', models.ImageField(default='infrastructure/documents/data_exchange_formats/images/none/default.jpg', null=True, upload_to='infrastructure/documents/data_exchange_formats/images/')),
                ('data_exchange_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.DataExchangeFormatService')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureDescriptionDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='infrastructure/documents/infrastructure_description/')),
                ('image', models.ImageField(default='infrastructure/documents/infrastructure_description/images/none/default.jpg', null=True, upload_to='infrastructure/documents/infrastructure_description/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalInterfaceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='services/technical_interfaces/documents/')),
                ('image', models.ImageField(default='services/technical_interfaces/documents/images/none/default.jpg', null=True, upload_to='services/technical_interfaces/documents/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dataexchangeformat',
            name='infrastructure_documents',
        ),
        migrations.RemoveField(
            model_name='dataexchangeformat',
            name='infrastructure_reference_documents',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contact_points',
        ),
        migrations.RemoveField(
            model_name='application',
            name='data_exchange_formats',
        ),
        migrations.RemoveField(
            model_name='application',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='application',
            name='files',
        ),
        migrations.RemoveField(
            model_name='infrastructuredescription',
            name='infrastructure_documents',
        ),
        migrations.RemoveField(
            model_name='infrastructuredescription',
            name='technical_interface_bindings',
        ),
        migrations.RemoveField(
            model_name='infrastructureprofile',
            name='technical_interface_bindings',
        ),
        migrations.RemoveField(
            model_name='service',
            name='contact_points',
        ),
        migrations.RemoveField(
            model_name='service',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='technicalinterface',
            name='data_exchange_formats',
        ),
        migrations.RemoveField(
            model_name='technicalinterface',
            name='end_points',
        ),
        migrations.RemoveField(
            model_name='technicalinterface',
            name='service_documents',
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationfile',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='registry.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantdocument',
            name='participant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='community.Participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicedocument',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface', to='registry.InfrastructureDescription'),
        ),
        migrations.DeleteModel(
            name='ContactPoint',
        ),
        migrations.DeleteModel(
            name='DataExchangeFormat',
        ),
        migrations.DeleteModel(
            name='EndPoint',
        ),
        migrations.DeleteModel(
            name='InfrastructureDocument',
        ),
        migrations.DeleteModel(
            name='TechnicalInterfaceBinding',
        ),
        migrations.AddField(
            model_name='technicalinterfacedocument',
            name='technical_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.TechnicalInterface'),
        ),
        migrations.AddField(
            model_name='infrastructuredescriptiondocument',
            name='infrastructure_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.InfrastructureDescription'),
        ),
        migrations.AddField(
            model_name='dataexchangeformatservice',
            name='technical_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exchange_formats', to='registry.TechnicalInterface'),
        ),
        migrations.AddField(
            model_name='dataexchangeformatapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exchange_formats', to='registry.Application'),
        ),
        migrations.AddField(
            model_name='dataexchangeformatapplication',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(to='registry.InfrastructureReferenceDocument'),
        ),
    ]
