# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_contactpointapplication_contactpointparticipant_contactpointservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalinterface',
            name='name',
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
