# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20170521_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface', to='registry.InfrastructureDescription'),
        ),
    ]
