# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_auto_20170521_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='services/end_points/images/none/default.jpg', upload_to='services/end_points/images/')),
                ('address', models.URLField(max_length=255, null=True)),
                ('technical_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_points', to='registry.TechnicalInterface')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalInterfaceBindingDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='infrastructure/technical_interface_bindings/images/none/default.jpg', upload_to='infrastructure/technical_interface_bindings/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalInterfaceBindingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(default='infrastructure/technical_interface_bindings/images/none/default.jpg', upload_to='infrastructure/technical_interface_bindings/images/')),
                ('infrastructure_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface_bindings', to='registry.InfrastructureProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='infrastructuredescription',
            name='name',
        ),
        migrations.AddField(
            model_name='technicalinterfacebindingdescription',
            name='infrastructure_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface_bindings', to='registry.InfrastructureDescription'),
        ),
    ]
