# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_auto_20170522_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpointapplication',
            name='image',
            field=models.ImageField(blank=True, default='applications/contact_points/images/none/default.svg', upload_to='applications/contact_points/images/'),
        ),
        migrations.AlterField(
            model_name='contactpointparticipant',
            name='image',
            field=models.ImageField(blank=True, default='participants/contact_points/images/none/default.svg', upload_to='participants/contact_points/images/'),
        ),
    ]
