# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_auto_20170522_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncategory',
            name='name',
            field=models.CharField(choices=[('BRAZIL', 'Brazil'), ('AFRICA', 'Africa'), ('ASIA', 'Asia'), ('EUROPE', 'Europe'), ('GLOBAL', 'Global'), ('NORTH AMERICA', 'North America'), ('OCEANIA', 'Oceania'), ('SOUTH AMERICA', 'South America')], max_length=50, unique=True),
        ),
    ]
