# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_auto_20170522_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexchangeformatapplication',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, to='registry.InfrastructureReferenceDocument'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservice',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, to='registry.InfrastructureReferenceDocument'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='data_standards',
            field=models.ManyToManyField(blank=True, related_name='technical_interfaces', to='registry.DataStandard'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_description',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface', to='registry.InfrastructureDescription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_interfaces', to='registry.InfrastructureProfile'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, related_name='technical_interfaces', to='registry.InfrastructureReferenceDocument'),
        ),
    ]
