# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_auto_20170523_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_description',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface', to='registry.InfrastructureDescription'),
        ),
    ]
