# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_auto_20170523_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructuredescription',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, related_name='infrastructure_description', to='registry.InfrastructureReferenceDocument'),
        ),
    ]
