# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_auto_20170523_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructuredescription',
            name='technical_interface',
        ),
        migrations.AddField(
            model_name='technicalinterface',
            name='infrastructure_description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface', to='registry.InfrastructureDescription'),
        ),
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='community.Participant'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='data_standards',
            field=models.ManyToManyField(blank=True, null=True, related_name='technical_interfaces', to='registry.DataStandard'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, null=True, related_name='technical_interfaces', to='registry.InfrastructureReferenceDocument'),
        ),
    ]
