# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0026_auto_20170523_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalinterface',
            name='data_standards',
            field=models.ManyToManyField(blank=True, related_name='technical_interfaces', to='registry.DataStandard'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, related_name='technical_interfaces', to='registry.InfrastructureReferenceDocument'),
        ),
    ]
