# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0027_auto_20170523_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='community.Participant'),
            preserve_default=False,
        ),
    ]
