# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_auto_20170523_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpointapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='registry.Application'),
        ),
    ]
