# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0031_auto_20170525_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='next_state',
            new_name='new_state',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='current_state',
        ),
        migrations.AddField(
            model_name='workflow',
            name='old_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows_from', to='registry.RegistrationStatusCategory'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='application',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='contactpointapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='contactpointapplication',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='contactpointparticipant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='contactpointparticipant',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='contactpointservice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='contactpointservice',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplication',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservice',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='datastandard',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='datastandard',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescription',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='infrastructureprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='infrastructureprofile',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='service',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingdescription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingdescription',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingprofile',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
