# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0033_workflow_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastandard',
            options={'verbose_name': 'data standard'},
        ),
        migrations.AlterModelOptions(
            name='endpoint',
            options={'verbose_name': 'end point'},
        ),
        migrations.AlterModelOptions(
            name='infrastructuredescription',
            options={'verbose_name': 'infrastructure description'},
        ),
        migrations.AlterModelOptions(
            name='infrastructureprofile',
            options={'verbose_name': 'infrastructure profile'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service'},
        ),
        migrations.AlterModelOptions(
            name='subscriptioncontenttype',
            options={'verbose_name': 'subscription content type'},
        ),
        migrations.AlterModelOptions(
            name='technicalinterface',
            options={'verbose_name': 'technical interface'},
        ),
        migrations.AlterModelOptions(
            name='technicalinterfacebindingdescription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='technicalinterfacebindingprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': 'workflow'},
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(choices=[('AERONAUTICAL INFORMATION MANAGEMENT', 'Aeronautical Information Management'), ('AIRPORT CDM', 'Airport CDM'), ('COLLISION AVOIDANCE', 'Collision Avoidance'), ('SURVEILLANCE INFRASTRUCTURE', 'Surveillance Infrastructure'), ('TRAFFIC SEQUENCING', 'Traffic Sequencing'), ('TRAFFIC SYNCHRONISATION', 'Traffic Synchronisation'), ('TRAJECTORY EXECUTION AND CONFORMANCE MONITORING', 'Trajectory Execution And Conformance Monitoring'), ('CNS INFRASTRUCTURE', 'CNS Infrastructure'), ('FLIGHT INFORMATION MANAGEMENT', 'Flight Information Management'), ('NAVIGTION INFRASTRUCTURE', 'Navigtion Infrastructure'), ('ROUTE DESIGN', 'Route Design'), ('SEPARATION PROVISION', 'Separation Provision'), ('TRAJECTORY PLANNING', 'Trajectory Planning'), ('AIRSPACE AND SURFACE STRUCTURE DESIGN', 'Airspace And Surface Structure Design'), ('ATM INFORMATION MANAGEMENT', 'ATM Information Management'), ('COMMUNICATION INFRASTRUCTURE', 'Communication Infrastructure'), ('METEOROLOGICAL INFORMATION', 'Meteorological Information'), ('ROUTE ASSIGNMENT AND GUIDANCE', 'Route Assignment And Guidance'), ('AIRSPACE AND SURFACE STRUCTURE ALLOCATION', 'Airspace And Surface Structure Allocation'), ('MET INFORMATION MANAGEMENT', 'MET Information Management'), ('AIRSPACE ACCESS', 'Airspace Access'), ('SHARED INFORMATION SERVICE MANAGEMENT', 'Shared Information Service Management'), ('DEMAND AND CAPACITY BALANCING', 'Demand And Capacity Balancing'), ('CONFLICT MANAGEMENT', 'Conflict Management'), ('AIRPORT MANAGEMENT', 'Airport Management'), ('TRAJECTORY MANAGEMENT', 'Trajectory Management'), ('ATM NETWORK MANAGEMENT', 'ATM Network Management')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='activity_categories',
            field=models.ManyToManyField(related_name='applications', to='registry.ActivityCategory', verbose_name='ATM activity categories'),
        ),
        migrations.AlterField(
            model_name='application',
            name='consumed_services',
            field=models.ManyToManyField(related_name='applications', to='registry.Service', verbose_name='consumed services'),
        ),
        migrations.AlterField(
            model_name='application',
            name='data_categories',
            field=models.ManyToManyField(related_name='applications', to='registry.DataCategory', verbose_name='ATM data categories'),
        ),
        migrations.AlterField(
            model_name='application',
            name='data_standards',
            field=models.ManyToManyField(related_name='applications', to='registry.DataStandard', verbose_name='data standards'),
        ),
        migrations.AlterField(
            model_name='application',
            name='flight_phases',
            field=models.ManyToManyField(related_name='applications', to='registry.FlightPhaseCategory', verbose_name='flight phases'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(default='applications/profiles/images/none/default.jpg', upload_to='applications/profiles/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='application',
            name='implementation_maturity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.ImplementationMaturityCategory', verbose_name='implementation maurity'),
        ),
        migrations.AlterField(
            model_name='application',
            name='implementation_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.ImplementationStatusCategory', verbose_name='implementation status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='opensource',
            field=models.BooleanField(default=False, verbose_name='open source'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='community.Participant', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payable',
            field=models.BooleanField(default=False, verbose_name='payable'),
        ),
        migrations.AlterField(
            model_name='application',
            name='regions',
            field=models.ManyToManyField(related_name='applications', to='registry.RegionCategory', verbose_name='regions'),
        ),
        migrations.AlterField(
            model_name='application',
            name='registration_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.RegistrationStatusCategory', verbose_name='registration status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='reviewed'),
        ),
        migrations.AlterField(
            model_name='application',
            name='stakeholders',
            field=models.ManyToManyField(related_name='applications', to='registry.StakeholderCategory', verbose_name='stakeholders'),
        ),
        migrations.AlterField(
            model_name='application',
            name='version',
            field=models.CharField(max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='application',
            name='version_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.VersionCategory', verbose_name='version category'),
        ),
        migrations.AlterField(
            model_name='application',
            name='workflow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='registry.Workflow', verbose_name='workflow'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.Application', verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document',
            field=models.FileField(blank=True, upload_to='applications/documents/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='image',
            field=models.ImageField(blank=True, default='applications/documents/images/none/default.svg', upload_to='applications/documents/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='contactpointapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='registry.Application', verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='contactpointapplication',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contactpointapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactpointapplication',
            name='image',
            field=models.ImageField(blank=True, default='applications/contact_points/images/none/default.svg', upload_to='applications/contact_points/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='contactpointapplication',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactpointapplication',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='contactpointparticipant',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contactpointparticipant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactpointparticipant',
            name='image',
            field=models.ImageField(blank=True, default='participants/contact_points/images/none/default.svg', upload_to='participants/contact_points/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='contactpointparticipant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactpointparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='community.Participant', verbose_name='participant'),
        ),
        migrations.AlterField(
            model_name='contactpointparticipant',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='contactpointservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contactpointservice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactpointservice',
            name='image',
            field=models.ImageField(blank=True, default='services/contact_points/images/none/default.svg', upload_to='services/contact_points/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='contactpointservice',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactpointservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='registry.Service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='contactpointservice',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='datacategory',
            name='name',
            field=models.CharField(choices=[('AERONAUTICAL INFORMATION', 'Aeronautical Information'), ('METEOROLOGY', 'Meteorology'), ('ENVIRONMENT', 'Environment'), ('CAPACITY DEMAND AND FLOW', 'Capacity Demand and Flow'), ('SURVEILLANCE', 'Surveillance'), ('OTHER', 'Other')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exchange_formats', to='registry.Application', verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplication',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplication',
            name='image',
            field=models.ImageField(default='infrastructure/data_exchange_formats/profiles/images/none/default.svg', upload_to='infrastructure/data_exchange_formats/profiles/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplication',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, to='registry.InfrastructureReferenceDocument', verbose_name='infrastructure reference documents'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplication',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplication',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='data_exchange_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.DataExchangeFormatApplication', verbose_name='data exchange format'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='document',
            field=models.FileField(blank=True, upload_to='infrastructure/documents/data_exchange_formats/applications/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatapplicationdocument',
            name='image',
            field=models.ImageField(blank=True, default='infrastructure/documents/data_exchange_formats/applications/images/none/default.svg', upload_to='infrastructure/documents/data_exchange_formats/applications/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservice',
            name='image',
            field=models.ImageField(default='infrastructure/data_exchange_formats/profiles/images/none/default.svg', upload_to='infrastructure/data_exchange_formats/profiles/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservice',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, to='registry.InfrastructureReferenceDocument', verbose_name='infrastructure reference documents'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservice',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservice',
            name='technical_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exchange_formats', to='registry.TechnicalInterface', verbose_name='technical interface'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservice',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='data_exchange_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.DataExchangeFormatService', verbose_name='data exchange format'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='document',
            field=models.FileField(blank=True, upload_to='infrastructure/data_exchange_formats/documents/services/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='dataexchangeformatservicedocument',
            name='image',
            field=models.ImageField(blank=True, default='infrastructure/data_exchange_formats/documents/services/images/none/applications/default.svg', upload_to='infrastructure/data_exchange_formats/documents/services/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='datastandard',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='datastandard',
            name='image',
            field=models.ImageField(default='infrastructure/data_standards/profiles/images/none/default.svg', upload_to='infrastructure/data_standards/profiles/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='datastandard',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(related_name='data_standards', to='registry.InfrastructureReferenceDocument', verbose_name='infrastructure reference documents'),
        ),
        migrations.AlterField(
            model_name='datastandard',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='datastandard',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='address',
            field=models.URLField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='image',
            field=models.ImageField(default='services/end_points/images/none/default.svg', upload_to='services/end_points/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='technical_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_points', to='registry.TechnicalInterface', verbose_name='technical interface'),
        ),
        migrations.AlterField(
            model_name='flightphasecategory',
            name='name',
            field=models.CharField(choices=[('AIRPORT RAMP', 'Airport (ramp)'), ('TAKE OFF', 'Take Off'), ('DEPARTURE', 'Departure'), ('EN-ROUTE', 'En-route'), ('OCEANIC', 'Oceanic'), ('ARRIVAL', 'Arrival')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='implementationmaturitycategory',
            name='name',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('PROTOTYPE', 'Prototype')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='implementationstatuscategory',
            name='name',
            field=models.CharField(choices=[('CURRENT AND SUPPORTED', 'Read for consumption'), ('TERMINATED', 'Terminated'), ('UNDER DEVELOPMENT', 'Under development')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescription',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescription',
            name='image',
            field=models.ImageField(default='infrastructure/infrastructure_description/images/none/default.svg', upload_to='infrastructure/infrastructure_description/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescription',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, related_name='infrastructure_description', to='registry.InfrastructureReferenceDocument', verbose_name='infrastructure reference documents'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescription',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='document',
            field=models.FileField(blank=True, upload_to='infrastructure/documents/infrastructure_description/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='image',
            field=models.ImageField(blank=True, default='infrastructure/infrastructure_description/documents/images/none/default.svg', upload_to='infrastructure/infrastructure_description/documents/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='infrastructuredescriptiondocument',
            name='infrastructure_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.InfrastructureDescription', verbose_name='infrastructure description'),
        ),
        migrations.AlterField(
            model_name='infrastructureprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='infrastructureprofile',
            name='image',
            field=models.ImageField(default='infrastructure/profiles/images/none/default.svg', upload_to='infrastructure/profiles/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='infrastructureprofile',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(related_name='infrastructure_profiles', to='registry.InfrastructureReferenceDocument', verbose_name='infrastructure reference documents'),
        ),
        migrations.AlterField(
            model_name='infrastructureprofile',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='infrastructureprofile',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='document',
            field=models.FileField(blank=True, upload_to='infrastructure/reference_documents/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='infrastructurereferencedocument',
            name='image',
            field=models.ImageField(blank=True, default='infrastructure/reference_documents/images/none/default.svg', upload_to='infrastructure/reference_documents/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='document',
            field=models.FileField(blank=True, upload_to='participants/documents/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='image',
            field=models.ImageField(blank=True, default='participants/documents/images/none/default.svg', upload_to='participants/documents/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='participantdocument',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='community.Participant', verbose_name='participant'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='document',
            field=models.FileField(blank=True, upload_to='swim/reference_documents/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='image',
            field=models.ImageField(blank=True, default='swim/reference_documents/images/none/default.svg', upload_to='swim/reference_documents/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='regioncategory',
            name='name',
            field=models.CharField(choices=[('BRAZIL', 'Brazil'), ('AFRICA', 'Africa'), ('ASIA', 'Asia'), ('EUROPE', 'Europe'), ('GLOBAL', 'Global'), ('NORTH AMERICA', 'North America'), ('OCEANIA', 'Oceania'), ('SOUTH AMERICA', 'South America')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='registrationstatuscategory',
            name='name',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATION', 'Validation'), ('REGISTERED', 'Registered')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='activity_categories',
            field=models.ManyToManyField(related_name='services', to='registry.ActivityCategory', verbose_name='ATM activity categories'),
        ),
        migrations.AlterField(
            model_name='service',
            name='data_categories',
            field=models.ManyToManyField(related_name='services', to='registry.DataCategory', verbose_name='ATM data categories'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='flight_phases',
            field=models.ManyToManyField(related_name='services', to='registry.FlightPhaseCategory', verbose_name='flight phases'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/profiles/images/none/default.svg', upload_to='services/profiles/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='implementation_maturity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.ImplementationMaturityCategory', verbose_name='implementation maturity'),
        ),
        migrations.AlterField(
            model_name='service',
            name='implementation_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.ImplementationStatusCategory', verbose_name='implementation status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='community.Participant', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='service',
            name='regions',
            field=models.ManyToManyField(related_name='services', to='registry.RegionCategory', verbose_name='regions'),
        ),
        migrations.AlterField(
            model_name='service',
            name='registration_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.RegistrationStatusCategory', verbose_name='registration status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='reviewed'),
        ),
        migrations.AlterField(
            model_name='service',
            name='stakeholders',
            field=models.ManyToManyField(related_name='services', to='registry.StakeholderCategory', verbose_name='stakeholders'),
        ),
        migrations.AlterField(
            model_name='service',
            name='technical_interface',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='registry.TechnicalInterface', verbose_name='technical interface'),
        ),
        migrations.AlterField(
            model_name='service',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='service',
            name='version_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.VersionCategory', verbose_name='version category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='workflow',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='registry.Workflow', verbose_name='workflow'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='document',
            field=models.FileField(blank=True, upload_to='services/documents/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='image',
            field=models.ImageField(blank=True, default='services/documents/images/none/default.svg', upload_to='services/documents/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.Service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='stakeholdercategory',
            name='name',
            field=models.CharField(choices=[('AIRPORT OPERATOR', 'Airport Operator'), ('AIRSPACE USER', 'Airspace User'), ('ANSP', 'ANSP'), ('NETWORK MANAGER', 'Network Manager')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subscriptioncontenttype',
            name='name',
            field=models.CharField(choices=[('AIRM MODEL', 'AIRM Model'), ('COMPLIANCE REFERENCE DOCUMENT', 'Compliance Reference Document'), ('CONTACT POINT', 'Contact Point'), ('ORGANISATION DOCUMENT', 'Organisation Document'), ('GENERAL DOCUMENT', 'General Document'), ('INFORMATION REFERENCE DOCUMENT', 'Information Reference Document'), ('INFRASTRUCTURE PROFILE', 'Infrastructure Profile'), ('REFERENCE DOCUMENT', 'Reference Document'), ('INFRASTRUCTURE STANDARD', 'Infrastructure Standard'), ('INTERFACE', 'Interface'), ('ORGANISATION', 'Organisation'), ('PROPRIETARY DATA EXCHANGE FORMAT', 'Proprietary Data Exchange Format'), ('SERVICE IMPLEMENTATION', 'Service Implementation'), ('SERVICE COMPLIANCE CLAIM', 'Service Compliance Claim'), ('SERVICE DEFINITION', 'Service Definition'), ('SERVICE DEFINITION PROGRESS', 'Service Definition Progress'), ('SERVICE DOCUMENT', 'Service Document'), ('SERVICE END POINT', 'Service End Point'), ('SERVICE LOGICAL MODEL', 'Service Logical Model'), ('SERVICE REFERENCE DOCUMENT', 'Service Reference Document'), ('DATA STANDARD', 'Data Standard')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='data_standards',
            field=models.ManyToManyField(blank=True, related_name='technical_interfaces', to='registry.DataStandard', verbose_name='data standards'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='image',
            field=models.ImageField(default='services/technical_interfaces/images/none/default.svg', upload_to='services/technical_interfaces/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface', to='registry.InfrastructureDescription', verbose_name='infrastructure description'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_interfaces', to='registry.InfrastructureProfile', verbose_name='infrastructure profile'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='infrastructure_reference_documents',
            field=models.ManyToManyField(blank=True, related_name='technical_interfaces', to='registry.InfrastructureReferenceDocument', verbose_name='infrastructure reference documents'),
        ),
        migrations.AlterField(
            model_name='technicalinterface',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingdescription',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingdescription',
            name='image',
            field=models.ImageField(default='infrastructure/technical_interface_bindings/images/none/default.svg', upload_to='infrastructure/technical_interface_bindings/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingdescription',
            name='infrastructure_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface_bindings', to='registry.InfrastructureDescription', verbose_name='infrastructure description'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingdescription',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingprofile',
            name='image',
            field=models.ImageField(default='infrastructure/technical_interface_bindings/images/none/default.svg', upload_to='infrastructure/technical_interface_bindings/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingprofile',
            name='infrastructure_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_interface_bindings', to='registry.InfrastructureProfile', verbose_name='infrastructure profile'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacebindingprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='document',
            field=models.FileField(blank=True, upload_to='services/technical_interfaces/documents/', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='image',
            field=models.ImageField(blank=True, default='services/technical_interfaces/documents/images/none/default.svg', upload_to='services/technical_interfaces/documents/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='technicalinterfacedocument',
            name='technical_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.TechnicalInterface', verbose_name='technical interface'),
        ),
        migrations.AlterField(
            model_name='versioncategory',
            name='name',
            field=models.CharField(choices=[('CURRENT AND SUPPORTED', 'Current and Supported'), ('NON SUPPORTED', 'Non Supported'), ('OBSOLETE BUT SUPPORTED', 'Obsolete but Supported'), ('UPCOMING NOT SUPPORTED', 'Upcoming not Supported')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='community.Profile', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='new_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows_to', to='registry.RegistrationStatusCategory', verbose_name='new state'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='old_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows_from', to='registry.RegistrationStatusCategory', verbose_name='old state'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='previous_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Workflow', verbose_name='previous node'),
        ),
    ]
