# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0034_auto_20170601_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='approved',
        ),
    ]
