# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0038_auto_20170601_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequestservice',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='registry.Workflow', verbose_name='workflow'),
        ),
    ]
