# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0040_auto_20170601_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='displayable',
            new_name='reviewed',
        ),
        migrations.AlterField(
            model_name='service',
            name='registration_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.RegistrationStatusCategory', verbose_name='registration status'),
        ),
    ]
