# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0042_auto_20170601_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='community.Profile', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='reviewed'),
        ),
    ]
