# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0045_auto_20170607_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='activity_categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='registry.ActivityCategory', verbose_name='ATM activity categories'),
        ),
        migrations.AlterField(
            model_name='service',
            name='data_categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='registry.DataCategory', verbose_name='ATM data categories'),
        ),
        migrations.AlterField(
            model_name='service',
            name='flight_phases',
            field=models.ManyToManyField(blank=True, related_name='services', to='registry.FlightPhaseCategory', verbose_name='flight phases'),
        ),
        migrations.AlterField(
            model_name='service',
            name='implementation_maturity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.ImplementationMaturityCategory', verbose_name='implementation maturity'),
        ),
        migrations.AlterField(
            model_name='service',
            name='implementation_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.ImplementationStatusCategory', verbose_name='implementation status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='services', to='registry.RegionCategory', verbose_name='regions'),
        ),
        migrations.AlterField(
            model_name='service',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='services', to='registry.StakeholderCategory', verbose_name='stakeholders'),
        ),
        migrations.AlterField(
            model_name='service',
            name='version_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registry.VersionCategory', verbose_name='version category'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='previous_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Workflow', verbose_name='previous node'),
        ),
    ]
