# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0050_auto_20171109_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationstatuscategory',
            name='name',
            field=models.CharField(choices=[('CURRENT AND SUPPORTED', 'Ready for consumption'), ('TERMINATED', 'Terminated'), ('UNDER DEVELOPMENT', 'Under development')], max_length=50, unique=True, verbose_name='name'),
        ),
    ]
