# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('AIRSPACE COMPANY', 'Airspace company'), ('RESEARCH ORGANIZATION', 'Research Organization'), ('AIRPORT', 'Airport'), ('AERODROME', 'Aerodrome'), ('RESEARCH INSTITUTION', 'Research Institution'), ('PUBLIC AGENCY', 'Public Agency'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='picture',
            field=models.ImageField(default='participants/None/default.jpg', upload_to='participants/'),
        ),
    ]
