# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20170518_1644'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='contact_points',
            field=models.ManyToManyField(related_name='participants', to='registry.ContactPoint'),
        ),
        migrations.AddField(
            model_name='participant',
            name='documentations',
            field=models.ManyToManyField(related_name='participants', to='registry.ParticipantDocument'),
        ),
    ]
