# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20170514_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='picture',
            field=models.ImageField(default='participants/none/default.jpg', upload_to='participants/'),
        ),
    ]
