# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20170518_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='documentations',
            new_name='documents',
        ),
    ]
