# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20170519_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='community.Participant'),
        ),
    ]
