# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_profile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_organizations',
            field=models.ManyToManyField(related_name='followers', to='community.Participant'),
        ),
    ]
