# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_participant_displayable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='displayable',
            new_name='reviewed',
        ),
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(default='participants/profiles/images/none/default.svg', upload_to='participants/profiles/images/'),
        ),
    ]
