# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20170520_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='contact_points',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='documents',
        ),
    ]
