# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20170521_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
