# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20170522_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
