# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20170601_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'participant'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile'},
        ),
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'verbose_name': 'registration request'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.ParticipantCategory', verbose_name='participant category'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(default='participants/profiles/images/none/default.svg', upload_to='participants/profiles/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='reviewed'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='participantcategory',
            name='name',
            field=models.CharField(choices=[('AIRSPACE COMPANY', 'Airspace company'), ('RESEARCH ORGANIZATION', 'Research Organization'), ('AIRPORT', 'Airport'), ('AERODROME', 'Aerodrome'), ('RESEARCH INSTITUTION', 'Research Institution'), ('PUBLIC AGENCY', 'Public Agency'), ('OTHER', 'Other')], max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following_organizations',
            field=models.ManyToManyField(related_name='followers', to='community.Participant', verbose_name='following organizations'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification_frequency',
            field=models.CharField(choices=[('NEVER', 'Never'), ('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='NEVER', max_length=10, verbose_name='notification frequency'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='community.Participant', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_activity',
            field=models.ManyToManyField(related_name='profiles', to='registry.ActivityCategory', verbose_name='ATM activity subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_content_type',
            field=models.ManyToManyField(related_name='profiles', to='registry.SubscriptionContentType', verbose_name='content type subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_data',
            field=models.ManyToManyField(related_name='profiles', to='registry.DataCategory', verbose_name='ATM data subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_flight_phase',
            field=models.ManyToManyField(related_name='profiles', to='registry.FlightPhaseCategory', verbose_name='flight phases subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_region',
            field=models.ManyToManyField(related_name='profiles', to='registry.RegionCategory', verbose_name='region subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_stakeholder',
            field=models.ManyToManyField(related_name='profiles', to='registry.StakeholderCategory', verbose_name='stakeholder subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='note',
            field=models.TextField(verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='role',
            field=models.CharField(max_length=255, verbose_name='institutional role'),
        ),
    ]
