# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0043_auto_20170601_2304'),
        ('community', '0014_auto_20170601_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_services',
            field=models.ManyToManyField(related_name='followers', to='registry.Service', verbose_name='following services'),
        ),
    ]
