# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_auto_20170607_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_activity',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='registry.ActivityCategory', verbose_name='ATM activity subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_content_type',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='registry.SubscriptionContentType', verbose_name='content type subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_data',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='registry.DataCategory', verbose_name='ATM data subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_flight_phase',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='registry.FlightPhaseCategory', verbose_name='flight phases subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_region',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='registry.RegionCategory', verbose_name='region subscriptions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions_stakeholder',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='registry.StakeholderCategory', verbose_name='stakeholder subscriptions'),
        ),
    ]
