# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_auto_20170607_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='reviewed',
            field=models.BooleanField(default=True, verbose_name='reviewed'),
        ),
    ]
